WITH ctePatient AS (
    SELECT  
        PARSE_JSON(_airbyte_data):address[0].city::STRING AS address_city,
        PARSE_JSON(_airbyte_data):address[0].line[0]::STRING AS address_line1,
        PARSE_JSON(_airbyte_data):address[0].line[1]::STRING AS address_line2,
        PARSE_JSON(_airbyte_data):address[0].postalCode::STRING AS address_postal_code,
        PARSE_JSON(_airbyte_data):address[0].state::STRING AS address_state_code,
        PARSE_JSON(_airbyte_data):birthDate::STRING AS core_birth_date,
        PARSE_JSON(_airbyte_data):deceasedDateTime::STRING AS core_deceased_date_time,
        PARSE_JSON(_airbyte_data):gender::STRING AS core_gender,
        PARSE_JSON(_airbyte_data):id::STRING AS patient_id,
        PARSE_JSON(_airbyte_data):name[0].family::STRING AS name_family,
        PARSE_JSON(_airbyte_data):name[0].given[0]::STRING AS name_given,
        PARSE_JSON(_airbyte_data):name[0].given[1]::STRING AS name_middle,
        PARSE_JSON(_airbyte_data):name[0].use::STRING AS name_use,
        PARSE_JSON(_airbyte_data):resourceType::STRING AS name_resource_type,
        PARSE_JSON(_airbyte_data):identifier[1].period.start::STRING AS identifier_period_start,
    FROM {{source("airbyte_raw_patient", "landing_patient_external_table")}},
         LATERAL FLATTEN(INPUT => PARSE_JSON(_airbyte_data):extension) i
)
SELECT
    abs(patient_id) as patient_id,
    null as core_active,
    core_gender,
    core_birth_date,
    null as core_deceased_boolean,
    core_deceased_date_time,
    null as core_marital_status_code,
    null as misc_multiple_birth,
    null as misc_contact,
    null as misc_communication,
    null as misc_general_practitioner,
    null as misc_managing_organization,
    null as misc_link,
    null as misc_extension,
    null as identifier_use,
    null as identifier_type_code,
    null as identifier_system,
    null as identifier_value,
    identifier_period_start,
    null as identifier_period_end,
    null as identifier_assigner,
    name_use,
    null as name_text,
    name_family,
    name_given,
    name_middle,
    null as name_prefix,
    null as name_suffix,
    null as name_period_start,
    null as name_period_end,
    null as telecom_system,
    null as telecom_value,
    null as telecom_use,
    null as telecom_rank,
    null as telecom_period_start,
    null as telecom_period_end,
    null as address_use,
    null as address_type,
    null as address_text,
    address_line1,
    address_line2,
    null as address_line3,
    null as address_line4,
    address_city,
    address_state_code,
    address_postal_code,
    null as address_country,
    null as address_period_start,
    null as address_period_end,
    name_resource_type,
FROM ctePatient