data_transformation:
  outputs:
    dev:
      type: <snowflake>
      account: hmb88115.us-east-1 (snowflake_account)
      user: snowflake_username
      password: snowflake_pw
      role: snowflake_role
      database: snowflake_database
      warehouse: snowflake_warehouse
      schema: snowflake_schema
      threads: 4
      client_session_keep_alive: true
  target: dev


