version: 2

sources:
  - name: airbyte_raw_patient
    database: AIRBYTE_DB
    schema: ICEBERG
    tables:
      - name: landing_patient_external_table
        columns:
          - name: _airbyte_ab_id
            description: ID
            tests:
              - unique
              - not_null




